version: '3.9'

services:

  api_server:
    container_name: api_server
    build:
      context: ./backend
      network: host
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - CARD_COUNTER=1
      - ACCOUNT_COUNTER=1
      - CONTRACT_COUNTER=1

    env_file:
      - ./backend/.env
    networks:
      postgres_net:
    depends_on:
      - postgresql
    command: python3 online_bank/manage.py runserver 0.0.0.0:8000

  adminer:
    image: adminer
    restart: always
    networks:
      postgres_net:
    ports:
      - 8080:8080

  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    networks:
      postgres_net:
    volumes:
      - data-volume:/var/lib/postgresql:ro
    env_file:
      - .env.db

networks:
  postgres_net:
    name: postgres_net

volumes:
  data-volume:
