version: '3.9'

services:

  adminer:
    image: adminer
    restart: always
    networks:
      postgres_net:
    ports:
      - 8080:8080

  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    networks:
      postgres_net:
    volumes:
      - data-volume:/var/lib/postgresql:ro
    env_file:
      - .env.db


  api_server:
    container_name: api_server
    build:
      context: ./backend
      network: host
    restart: unless-stopped
    environment:
      - CARD_COUNTER=1
      - ACCOUNT_COUNTER=1
      - CONTRACT_COUNTER=1

    env_file:
      - ./backend/.env
    networks:
      postgres_net:
    depends_on:
      - postgresql
      - nginx
    command: python3 online_bank/manage.py runserver 0.0.0.0:8000

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    networks:
      bot_net:
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''


networks:
  postgres_net:
    name: postgres_net

volumes:
  data-volume:
